# 勿扰模式，该时间段内自动进入睡眠，避免监听
do_not_bother:
    enable: false # true: 开启; false: 关闭
    since: 23    # 开始时间
    till: 8      # 结束时间，如果比 since 小表示第二天

# snowboy 离线唤醒
hotword: 'snowboy.umdl'  # 唤醒词模型
silent_threshold: 20 # 判断为静音的阈值。环境比较吵杂的地方可以适当调大
recording_timeout: 15 # 录制的语音最大长度（秒）

# MAC地址，用于小智AI区分不同客户端
mac_address: 'cd:69:f9:9d:b9:ba'